# Generated by Django 4.0.6 on 2022-11-16 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_app.fields')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_app.generation')),
                ('q_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_app.qformat')),
            ],
        ),
    ]
