# Generated by Django 4.0.6 on 2022-11-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
