# Generated by Django 4.0.6 on 2022-11-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0003_alter_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('number', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ans', models.TextField()),
                ('trueORfalse', models.IntegerField()),
                ('posted_data', models.DateTimeField(auto_now_add=True)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_app.question')),
            ],
        ),
    ]
