# Generated by Django 4.0.6 on 2022-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0006_alter_question_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, verbose_name='お問い合わせ内容')),
                ('body', models.TextField(verbose_name='具体的に')),
            ],
        ),
    ]
